[package]
name = "enum-helper"
version = "0.1.0"
authors = ["uima <git@uimataso.com>"]
edition = "2024"
rust-version = "1.85"
description = "Yet another enum helper. Macros that generate common boilerplate for enums."
documentation = "https://docs.rs/enum-helper"
readme = "../README.md"
repository = "https://github.com/uimataso/enum-helper"
license = "MIT OR Apache-2.0"
keywords = ["enum", "macros", "proc-macros", "derive"]
categories = ["development-tools::procedural-macro-helpers"]

[features]
default = ["derive"]
derive = ["dep:enum-helper-derive"]

[dependencies]
enum-helper-derive = { version = "0.1.0", path = "../enum-helper-derive", optional = true }

[dev-dependencies]
assert2 = "0.4"
trybuild = "1.0"
